# Generated by Django 5.0.3 on 2024-05-27 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_audiorecord_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_audio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_audio', to=settings.AUTH_USER_MODEL),
        ),
    ]
