# Generated by Django 5.0.3 on 2024-05-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_audiorecord_group_alter_audiorecord_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioRecord',
        ),
    ]
