# Generated by Django 5.0.3 on 2024-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_message_body_message_prg_msg_message_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
