# Generated by Django 5.0.3 on 2024-05-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_message_prg_msg_alter_message_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='task',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
